# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 00:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('password', models.CharField(max_length=32)),
                ('isdelete', models.BooleanField(default=False)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
