# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', '男'), ('2', '女')], default='1', max_length=1, null=True, verbose_name='性别'),
        ),
    ]
