# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 12:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190122_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='head_show',
            field=models.ImageField(default='head/head_show.jpg', upload_to='head/%Y%m', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('1[35789]\\d{9}')], verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
